### PR TITLE
Feature/player crash fix

### LINKED ISSUE #533: Game crash
While using build #\352 connecting to my server (play.sunknights.fun), the game seems to crash shortly after logging in.

My server is running on bungeecord, the hub is on paper 1.15.2

Edit: More specifically, I am using waterfall instead of bungeecord, but I've tried switching back to bungeecord and it didn't make a difference. 

Console:
```
[01:34:23 INFO]: Spawned player LOOHP at -851.0178755243805 59.200000047683716 479.97444730902765
[01:34:23 INFO]: (debug) Unhandled block entity: minecraft:trapped_chest
[01:34:23 INFO]: (debug) Unhandled block entity: minecraft:trapped_chest
[01:34:23 INFO]: (debug) Unhandled block entity: minecraft:trapped_chest
[01:34:23 INFO]: (debug) Unhandled block entity: minecraft:trapped_chest
[01:34:23 INFO]: (debug) Unhandled block entity: minecraft:trapped_chest
[01:34:23 INFO]: (debug) Unhandled block entity: minecraft:trapped_chest
(Game crash here)
[01:34:51 INFO]: Player disconnected from remote. Reason: TIMED_OUT
```
Config:
```
# -----------------------------------------------
#   DragonProxy Configuration (25/03/20)
#   https://github.com/DragonetMC/DragonProxy
# -----------------------------------------------
# DO NOT CHANGE THIS VARIABLE!!!!!!
config-version: 2
# DO NOT CHANGE THIS VARIABLE!!!!!!

locale: 'EN'

# The IP and port the proxy will listen for connections on
# '0.0.0.0' will bind to all IP addresses available on your device
bind-address: '0.0.0.0'
bind-port: 19132

# The MOTD that will be shown on the MCPE server list
motd: 'DragonProxy'
motd2: 'https://github.com/DragonetMC/DragonProxy'

# The maximum amount of players that can join the proxy
max-players: 100

# The IP and port of the remote server to connect to
remote-address: 'play.sunknights.fun'
remote-port: 25565

# The authentication method used for connecting to the remote server.
# Accepted values:
#   credentials   : This will display a form when you join the proxy asking you to enter your Mojang credentials
#   offline       :  No authentication, cant join premium servers such as Hypixel
remote-auth: credentials

# Whether or not Bedrock clients should be authenticated with xbox live
xbox-auth: false

# Whether or not to use the motd and player count of the primary remote server
ping-passthrough: true

# Player gameplay related settings
player-settings:
  # Whether or not to translate commands sent from the remote server and display
  # them on the Bedrock client. This is currently experimental.
  enable-commands: false

  # Whether or not to enable auto jump
  auto-jump: false

  # Whether or not to fetch skins from Mojang's servers
  fetch-skins: false

metrics:
  enabled: true
  # DO NOT CHANGE
  server-uuid: donotchange_serveruuid

# The amount of threads that will be used.
# Only change if you know what you are doing
thread-pool-size: 8
```

### PR DESCRIPTION
**Pull request by james090500**
Fixes crashes due to End_Gateway
Fixes crashes due to custom java tablist

This fixes #533

### CODE REVIEW

File: proxy/src/main/java/org/dragonet/proxy/network/session/ProxySession.java [hunk 1]
```diff
@@ -440,7 +440,7 @@ public void sendFakeStartGame(boolean disconnect) {
         sendPacket(playStatusPacket);
 
         if(!disconnect) {
-            cachedEntity = entityCache.newPlayer(1, entityId, new GameProfile(getAuthData().getIdentity(), getAuthData().getDisplayName()));
+            cachedEntity = entityCache.newPlayer(Integer.MIN_VALUE, entityId, new GameProfile(getAuthData().getIdentity(), getAuthData().getDisplayName()));
```
Comment (lukeeey) [inline proxy/src/main/java/org/dragonet/proxy/network/session/ProxySession.java]: You can undo this as it was fixed remember

File: proxy/src/main/java/org/dragonet/proxy/network/translator/java/player/PCPlayerListEntryTranslator.java [hunk 2]
```diff
@@ -42,8 +41,15 @@ public void translate(ProxySession session, ServerPlayerListEntryPacket packet)
...
+
+            if(entry.getDisplayName() == null || entry.getDisplayName().toString().isEmpty()) { return; }
+
             PlayerListPacket.Entry bedrockEntry = new PlayerListPacket.Entry(entry.getProfile().getId());
-            String displayName = entry.getDisplayName() != null ? MessageTranslator.translate(entry.getDisplayName()) : entry.getProfile().getName();
+            String displayName = entry.getProfile().getName();
+            //Check player name is a valid minecraft name
+            if(displayName == null || !displayName.matches("^[a-zA-Z0-9_]{0,17}+$")) {
+                return;
+            }
```
Comment (lukeeey) [inline proxy/src/main/java/org/dragonet/proxy/network/translator/java/player/PCPlayerListEntryTranslator.java:52]: If it’s not valid you still need to add them to the player list I believe to prevent issues with spawning fake players like npcs. Test it on the hive and hypixel and if there’s no crashes I’ll keep it in.

**Review by lukeeey — CHANGES_REQUESTED** [review]

File: proxy/src/main/java/org/dragonet/proxy/network/session/ProxySession.java (hunk 1 above)
Comment (james090500) [reply proxy/src/main/java/org/dragonet/proxy/network/session/ProxySession.java]: Fixed in ef6a33f

File: proxy/src/main/java/org/dragonet/proxy/network/translator/java/player/PCPlayerListEntryTranslator.java (hunk 2 above)
Comment (james090500) [reply proxy/src/main/java/org/dragonet/proxy/network/translator/java/player/PCPlayerListEntryTranslator.java:52]: Fixed in ef6a33f

**Comment by james090500** [comment]
This new changes also moves to using PlayerSkinPacket rather than the PlayerListPacket hack.

**Comment by lukeeey** [comment]
Did you even read the comment on that method? (i believe there was one). It has caused crashes in the past for me.

The player list hack was there for a reason.

**Review by lukeeey — APPROVED** [review]
